---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible==2.5.7 ansible-lint docker-py molecule pyOpenSSL PyYAML
  - ansible --version

script:
  - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  - molecule test -s default
  - molecule test -s default-ubuntu

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
